version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    assignees:
      - jault3
    reviewers:
      - jault3
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    assignees:
      - jault3
    reviewers:
      - jault3
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - jault3
    reviewers:
      - jault3
